### ISSUE TITLE
File paths do not cover webroot subdirs

### ISSUE THREAD

**Issue by winkelement** [ssuess/resourcespace-plugin-pdf_export#1]
When i have an RS installation in a subdirectory (e.g. /htdocs/rs) i get errors from /pdf_export/include/general.php not able to find some requested files (e.g. line137).

You use a path like 
`$versionstrfile = file_get_contents($_SERVER["DOCUMENT_ROOT"]. '/lib/tcpdf/composer.json');`

So for anyone not having his RS in the webroot dir it will break.

You can use $baseurl_short to get that part of the path like

`global $baseurl_short;`
....
`$versionstrfile = file_get_contents($_SERVER["DOCUMENT_ROOT"]. $baseurl_short . '/lib/tcpdf/composer.json');`

**Comment by ssuess** [comment]
Thanks for the report I will have a fix shortly!

**Comment by ssuess** [comment]
hm, after checking into it (and vaguely remembering that I went down this path before) it seems that on my system at least, using `$baseurl_short` will cause a failure (in many ways). Would it work for you if I replaced `$_SERVER["DOCUMENT_ROOT"]`with `'../../../'`? That way, everything should still work and be relative to the appropriate paths.

**Comment by ssuess** [comment]
fixed in https://github.com/ssuess/resourcespace-plugin-pdf_export/commit/3b48e7bf19c8334afda350a892c596ec85ca0da9
